package com.myteam.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Power implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String contract;
	private double wat;
	private double unitfee;
	private double fee;
	private java.lang.String rule;

	public Power() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getContract() {
		return this.contract;
	}

	public void setContract(java.lang.String contract) {
		this.contract = contract;
	}

	public double getWat() {
		return this.wat;
	}

	public void setWat(double wat) {
		this.wat = wat;
	}

	public double getUnitfee() {
		return this.unitfee;
	}

	public void setUnitfee(double unitfee) {
		this.unitfee = unitfee;
	}

	public double getFee() {
		return this.fee;
	}

	public void setFee(double fee) {
		this.fee = fee;
	}

	public java.lang.String getRule() {
		return this.rule;
	}

	public void setRule(java.lang.String rule) {
		this.rule = rule;
	}

	public Power(java.lang.String name, java.lang.String contract, double wat,
			double unitfee, double fee, java.lang.String rule) {
		this.name = name;
		this.contract = contract;
		this.wat = wat;
		this.unitfee = unitfee;
		this.fee = fee;
		this.rule = rule;
	}

	@Override
	public String toString() {
		return "Power [name=" + name + ", contract=" + contract + ", wat=" + wat + ", unitfee=" + unitfee + ", fee="
				+ fee + ", rule=" + rule + "]";
	}

	public String toCsv() {
		return getContract() + "," + getWat();
	}
}